#!/usr/bin/env python3
from __future__ import annotations

import argparse
import datetime as dt
import re
from pathlib import Path
from typing import Iterable

DATE_RE = re.compile(r"^Last verified:\s*(\d{4}-\d{2}-\d{2})\s*$", re.MULTILINE)
LINK_RE = re.compile(r"\[[^\]]+\]\(([^)]+)\)")
AUTO_MANAGED_BANNER = "<!-- AUTO-GENERATED BY scripts/doc_gardener.py -->"


class Finding:
    def __init__(self, code: str, path: Path, detail: str) -> None:
        self.code = code
        self.path = path
        self.detail = detail

    def key(self) -> tuple[str, str, str]:
        return (self.code, self.path.as_posix(), self.detail)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Scan docs for stale markers and link issues")
    parser.add_argument("--max-age-days", type=int, default=90)
    parser.add_argument(
        "--write-report",
        type=Path,
        default=Path("docs/generated/doc-gardener-report.md"),
        help="Path to write markdown report",
    )
    parser.add_argument(
        "--apply-plan",
        action="store_true",
        help="Write or clean docs/plans/active/doc-gardening.md based on findings",
    )
    parser.add_argument(
        "--autofix-last-verified",
        action="store_true",
        help="Auto-add missing Last verified markers to docs markdown files",
    )
    return parser.parse_args()


def iter_docs_files(docs_dir: Path) -> Iterable[Path]:
    for path in sorted(docs_dir.rglob("*.md")):
        if any(part.startswith(".") for part in path.parts):
            continue
        yield path


def parse_last_verified(content: str) -> dt.date | None:
    match = DATE_RE.search(content)
    if not match:
        return None
    try:
        return dt.date.fromisoformat(match.group(1))
    except ValueError:
        return None


def is_external(link: str) -> bool:
    return (
        link.startswith("http://")
        or link.startswith("https://")
        or link.startswith("mailto:")
        or link.startswith("#")
    )


def collect_findings(root: Path, max_age_days: int) -> list[Finding]:
    docs_dir = root / "docs"
    findings: list[Finding] = []

    if not docs_dir.exists():
        findings.append(Finding("missing_docs_dir", docs_dir, "docs directory does not exist"))
        return findings

    today = dt.date.today()

    for md_path in iter_docs_files(docs_dir):
        rel = md_path.relative_to(root)
        content = md_path.read_text(encoding="utf-8")

        last_verified = parse_last_verified(content)
        if last_verified is None:
            findings.append(Finding("missing_last_verified", rel, "missing 'Last verified: YYYY-MM-DD' marker"))
        else:
            age = (today - last_verified).days
            if age > max_age_days:
                findings.append(
                    Finding(
                        "stale_last_verified",
                        rel,
                        f"{last_verified.isoformat()} is {age} days old (max {max_age_days})",
                    )
                )

        for raw in LINK_RE.findall(content):
            link = raw.strip()
            if is_external(link):
                continue
            target = link.split("#", 1)[0].strip()
            if not target:
                continue
            if target.startswith("/"):
                findings.append(Finding("absolute_local_link", rel, f"absolute link is not allowed: {link}"))
                continue
            resolved = (md_path.parent / target).resolve()
            if not resolved.exists():
                findings.append(Finding("broken_local_link", rel, f"broken local link: {link}"))

    findings.sort(key=lambda item: item.key())
    return findings


def build_report(findings: list[Finding], max_age_days: int) -> str:
    lines: list[str] = []
    lines.append("# Doc Gardener Report")
    lines.append("")
    lines.append(AUTO_MANAGED_BANNER)
    lines.append("")
    lines.append(f"Policy: docs markdown files should have 'Last verified' markers not older than {max_age_days} days.")
    lines.append("")

    if not findings:
        lines.append("Status: healthy")
        lines.append("")
        lines.append("No issues detected.")
        lines.append("")
        return "\n".join(lines)

    lines.append("Status: action required")
    lines.append("")

    grouped: dict[str, list[Finding]] = {}
    for finding in findings:
        grouped.setdefault(finding.code, []).append(finding)

    for code in sorted(grouped):
        lines.append(f"## {code}")
        lines.append("")
        for finding in grouped[code]:
            lines.append(f"- `{finding.path.as_posix()}`: {finding.detail}")
        lines.append("")

    lines.append("## Next Actions")
    lines.append("")
    lines.append("- Update stale or missing Last verified markers after validating current behavior.")
    lines.append("- Fix broken local links in docs.")
    lines.append("- Keep docs/AGENTS alignment with docs/index.md as the entry point.")
    lines.append("")

    return "\n".join(lines)


def write_if_changed(path: Path, content: str) -> bool:
    if path.exists():
        current = path.read_text(encoding="utf-8")
        if current == content:
            return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    return True


def sync_active_plan(root: Path, findings: list[Finding]) -> bool:
    plan_path = root / "docs" / "plans" / "active" / "doc-gardening.md"

    if not findings:
        if plan_path.exists():
            existing = plan_path.read_text(encoding="utf-8")
            if AUTO_MANAGED_BANNER in existing:
                plan_path.unlink()
                return True
        return False

    lines: list[str] = []
    lines.append("# Doc Gardening Active Plan")
    lines.append("")
    lines.append(AUTO_MANAGED_BANNER)
    lines.append("")
    lines.append(f"Last verified: {dt.date.today().isoformat()}")
    lines.append("")
    lines.append("This plan is generated from current documentation drift findings.")
    lines.append("")
    lines.append("## Tasks")
    lines.append("")
    seen = set()
    for finding in findings:
        item = f"- [ ] `{finding.path.as_posix()}`: {finding.detail}"
        if item in seen:
            continue
        seen.add(item)
        lines.append(item)
    lines.append("")

    return write_if_changed(plan_path, "\n".join(lines))


def autofix_missing_last_verified(root: Path, findings: list[Finding]) -> int:
    today = dt.date.today().isoformat()
    targets = sorted({f.path for f in findings if f.code == "missing_last_verified"})
    changed = 0

    for rel_path in targets:
        path = root / rel_path
        if not path.exists() or path.suffix.lower() != ".md":
            continue

        content = path.read_text(encoding="utf-8")
        if "Last verified:" in content:
            continue

        lines = content.splitlines()
        if not lines:
            continue

        insert_idx = 1
        if len(lines) > 1 and lines[1].strip() == "":
            insert_idx = 2

        marker_block = [f"Last verified: {today}", ""]
        new_lines = lines[:insert_idx] + marker_block + lines[insert_idx:]
        new_content = "\n".join(new_lines)
        if content.endswith("\n"):
            new_content += "\n"

        path.write_text(new_content, encoding="utf-8")
        changed += 1

    return changed


def main() -> int:
    args = parse_args()
    root = Path(__file__).resolve().parent.parent

    findings = collect_findings(root, args.max_age_days)

    autofixed = 0
    if args.autofix_last_verified:
        autofixed = autofix_missing_last_verified(root, findings)
        findings = collect_findings(root, args.max_age_days)

    report = build_report(findings, args.max_age_days)
    report_changed = write_if_changed(root / args.write_report, report)

    plan_changed = False
    if args.apply_plan:
        plan_changed = sync_active_plan(root, findings)

    counts: dict[str, int] = {}
    for finding in findings:
        counts[finding.code] = counts.get(finding.code, 0) + 1

    print(f"Doc gardener findings: {len(findings)}")
    for code in sorted(counts):
        print(f"- {code}: {counts[code]}")
    print(f"Report updated: {'yes' if report_changed else 'no'}")
    if args.apply_plan:
        print(f"Active plan updated: {'yes' if plan_changed else 'no'}")
    if args.autofix_last_verified:
        print(f"Autofixed missing Last verified markers: {autofixed}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
