/**
 * Research Dossier Types
 *
 * The Classifier generates a "Research Dossier" that tells the Hunter exactly
 * what to search for. This moves strategic intelligence from the expensive
 * Hunter phase to the cheap Classifier phase.
 *
 * Problem Solved: "Claude" disambiguation happens for $0.0001 (Flash) instead
 * of $0.05 (Serper failures + re-runs).
 */

import { z } from 'zod';

/**
 * Tool categories with specific research strategies
 */
export const ToolCategorySchema = z.enum([
  'ai_model', // Claude, GPT-4, Gemini → focus on token pricing, context limits
  'api_platform', // Twilio, Stripe → focus on rate limits, per-request pricing
  'saas_collaboration', // Slack, Notion → focus on seat limits, storage quotas
  'saas_productivity', // Asana, Monday → focus on project limits, automation caps
  'crm_sales', // Salesforce, HubSpot → focus on contact limits, email caps
  'marketing_email', // Mailchimp, SendGrid → focus on subscriber limits, send rates
  'database_storage', // Airtable, MongoDB → focus on record/doc limits, storage
  'devtools', // GitHub, GitLab → focus on repo limits, CI minutes
  'legacy_defunct', // Flash, Silverlight → focus on shutdown date, alternatives
  'consumer_media', // Spotify, Netflix → focus on household limits, quality tiers
  'infrastructure', // AWS, Vercel → focus on usage-based pricing, egress fees
  'design_creative', // Figma, Canva → focus on editor limits, export restrictions
  'video_conferencing', // Zoom, Meet → focus on participant limits, recording storage
  'generic_saas', // Catch-all when category unclear
]);
export type ToolCategory = z.infer<typeof ToolCategorySchema>;

/**
 * Forensic targets map to our ConstraintType enum
 */
export const ForensicTargetSchema = z.enum([
  'record_count',
  'storage_gb',
  'api_requests_per_month',
  'api_rate_limit_per_sec',
  'seat_count',
  'project_count',
  'active_contacts',
  'message_credits',
  'concurrent_users',
  'bandwidth_gb',
  'build_minutes',
  'shutdown_status', // Special: for defunct detection
]);
export type ForensicTarget = z.infer<typeof ForensicTargetSchema>;

/**
 * The Research Dossier - Generated by Classifier, Consumed by Hunter
 */
export const ResearchDossierSchema = z.object({
  // Disambiguated tool name (e.g., "Claude" → "Anthropic Claude")
  normalized_tool_name: z.string(),

  // Tool category determines query strategy
  primary_category: ToolCategorySchema,

  // Targeted queries the Hunter MUST use (3-5 queries)
  scout_queries: z.array(z.string()).min(3).max(5),

  // Specific constraints to hunt for (maps to ConstraintType)
  forensic_targets: z.array(ForensicTargetSchema).min(1).max(5),

  // Confidence in classification (if low, Hunter may add generic queries)
  confidence: z.enum(['high', 'medium', 'low']).default('medium'),

  // Red flags for defunct detection
  red_flags: z.array(z.string()).optional(), // e.g., ["Adobe discontinued 2020", "No pricing page"]

  // Estimated API cost if this dossier is wrong (for tracking)
  risk_score: z.number().min(0).max(10).optional(),
});
export type ResearchDossier = z.infer<typeof ResearchDossierSchema>;

/**
 * Enhanced classification with dossier
 */
export const KeywordClassificationSchema = z.object({
  keyword: z.string(),
  type: z.enum(['best_list', 'comparison', 'alternatives', 'single_tool', 'informational', 'skip']),
  extracted_tools: z.array(z.string()),
  suggested_context: z.string().nullable(),

  // NEW: The Research Dossier
  research_dossier: ResearchDossierSchema.optional(),
});
export type KeywordClassification = z.infer<typeof KeywordClassificationSchema>;

/**
 * Category-specific query templates
 * LLM fills in {{tool}} and {{category_hint}} placeholders
 */
export const CATEGORY_QUERY_TEMPLATES: Record<ToolCategory, string[]> = {
  ai_model: [
    '{{tool}} pricing tokens vs subscription',
    '{{tool}} official docs models overview release notes',
    '{{tool}} context window rate limits model deprecations',
    '{{tool}} benchmark GPQA MMLU SWE-bench LiveBench official report',
    '{{tool}} API rate limits documentation',
    '{{tool}} hidden costs enterprise',
  ],
  api_platform: [
    '{{tool}} API pricing per request',
    '{{tool}} rate limits throttling',
    '{{tool}} overage charges costs',
    '{{tool}} free tier limits',
    '{{tool}} webhook quotas',
  ],
  saas_collaboration: [
    '{{tool}} seat limits per plan',
    '{{tool}} storage quota limits',
    '{{tool}} guest user billing',
    '{{tool}} SSO enterprise cost',
    '{{tool}} file upload restrictions',
  ],
  saas_productivity: [
    '{{tool}} project limits per plan',
    '{{tool}} automation quotas',
    '{{tool}} task limits free tier',
    '{{tool}} integration restrictions',
    '{{tool}} reporting limits',
  ],
  crm_sales: [
    '{{tool}} contact limits per plan',
    '{{tool}} email sending limits',
    '{{tool}} deal pipeline restrictions',
    '{{tool}} custom field limits',
    '{{tool}} API access tiers',
  ],
  marketing_email: [
    '{{tool}} subscriber limits pricing',
    '{{tool}} email sending rate limits',
    '{{tool}} automation limits',
    '{{tool}} contact import restrictions',
    '{{tool}} overage billing',
  ],
  database_storage: [
    '{{tool}} record count limits',
    '{{tool}} storage limits per base',
    '{{tool}} API rate limits',
    '{{tool}} attachment size limits',
    '{{tool}} automation run limits',
  ],
  devtools: [
    '{{tool}} repository limits',
    '{{tool}} CI/CD minutes quota',
    '{{tool}} storage limits artifacts',
    '{{tool}} collaborator limits',
    '{{tool}} API rate limits',
  ],
  legacy_defunct: [
    '{{tool}} shutdown date discontinued',
    '{{tool}} alternatives 2026',
    '{{tool}} end of life announcement',
    '{{tool}} migration guide',
    '{{tool}} emulator replacement',
  ],
  consumer_media: [
    '{{tool}} household sharing limits',
    '{{tool}} device limits',
    '{{tool}} quality tiers restrictions',
    '{{tool}} offline download limits',
    '{{tool}} family plan pricing',
  ],
  infrastructure: [
    '{{tool}} pricing calculator',
    '{{tool}} egress bandwidth costs',
    '{{tool}} free tier limits',
    '{{tool}} commitment discounts',
    '{{tool}} hidden fees charges',
  ],
  design_creative: [
    '{{tool}} editor limits seats',
    '{{tool}} export restrictions',
    '{{tool}} storage limits projects',
    '{{tool}} version history limits',
    '{{tool}} collaboration limits',
  ],
  video_conferencing: [
    '{{tool}} participant limits',
    '{{tool}} meeting duration limits',
    '{{tool}} recording storage limits',
    '{{tool}} cloud recording restrictions',
    '{{tool}} breakout room limits',
  ],
  generic_saas: [
    '{{tool}} pricing plans limits',
    '{{tool}} free tier restrictions',
    '{{tool}} user limits per plan',
    '{{tool}} hidden costs',
    '{{tool}} enterprise pricing',
  ],
};

/**
 * Category-specific forensic targets
 */
export const CATEGORY_FORENSIC_TARGETS: Record<ToolCategory, ForensicTarget[]> = {
  ai_model: ['api_requests_per_month', 'api_rate_limit_per_sec'],
  api_platform: ['api_requests_per_month', 'api_rate_limit_per_sec', 'message_credits'],
  saas_collaboration: ['seat_count', 'storage_gb', 'project_count'],
  saas_productivity: ['seat_count', 'project_count'],
  crm_sales: ['active_contacts', 'seat_count', 'message_credits'],
  marketing_email: ['active_contacts', 'message_credits', 'api_requests_per_month'],
  database_storage: ['record_count', 'storage_gb', 'api_requests_per_month'],
  devtools: ['project_count', 'storage_gb', 'build_minutes'],
  legacy_defunct: ['shutdown_status'],
  consumer_media: ['concurrent_users', 'storage_gb'],
  infrastructure: ['storage_gb', 'bandwidth_gb', 'api_requests_per_month'],
  design_creative: ['seat_count', 'storage_gb', 'project_count'],
  video_conferencing: ['concurrent_users', 'storage_gb'],
  generic_saas: ['seat_count', 'storage_gb'],
};
